name: Publish New Release
on:
  push:
    tags:
      - 'v*'

jobs:
  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  releases-matrix:
    name: Release Go Binary
    needs: create_release
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.20'

    - name: make dist
      run: mkdir dist

    - name: build
      run: go build -ldflags "-s -w" -o dist/gradescope_wrapper
      env:
        CGO_ENABLED: 0
        GOOS: ${{ matrix.goos }}
        GOARCH: ${{ matrix.goarch }}

    - name: additional items
      run: cp README.md dist/

    - name: Tar Folder
      if: ${{ matrix.goos != 'windows'}}
      run: tar czf ../release.tgz ./
      working-directory: dist


    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ needs.create_release.outputs.upload_url }}
        asset_name: gradescope_wrapper-${{ matrix.goos }}-${{ matrix.goarch }}.${{ matrix.goos == 'windows' && 'zip' || 'tgz' }}
        asset_path: ${{ matrix.goos == 'windows' && 'release.zip' || 'release.tgz' }}
        asset_content_type: application/octet-stream
